FORM_URL= https://${EGNAPA_HOST}/e/admin/naanq2e.html
DESTDIR=  $(HOME)/sv/cur/apache2/htdocs/e/admin/
WEBFILES= form2naa naanq2e.html q2e.pl

all:
	cp -pr $(WEBFILES) $(DESTDIR)
	@echo "Visit $(FORM_URL) to test."
